[package]
name = "tracker"
version = "0.1.0"
authors = ["James Hunt <james@niftylogic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.13"
iron = "0.6"
router = "0.6"
lazy_static = "1.4"
